[pytest]
filterwarnings =
    ignore:authlib\.jose module is deprecated, please use joserfc instead\.:authlib.deprecate.AuthlibDeprecationWarning
    ignore:\[EXPERIMENTAL\] feature FeatureName\.PLUGGABLE_AUTH is enabled\.:UserWarning
